### ISSUE TITLE
OSError: [WinError 193] %1 не является приложением Win32

### ISSUE THREAD

**Issue by artizzq** [SerezD/scheduling_utils#1]
```
Traceback (most recent call last):
  File "C:\Users\*****\*****\vqvae-vqgan-pytorch-lightning-master\vqvae\train.py", line 15, in <module>
    from vqvae.model import VQVAE
  File "C:\Users\*****\*****\vqvae-vqgan-pytorch-lightning-master\vqvae\model.py", line 6, in <module>
    from scheduling_utils.schedulers_cpp import LinearScheduler, CosineScheduler, LinearCosineScheduler
  File "C:\Users\*****\*****\*****\venv\lib\site-packages\scheduling_utils\schedulers_cpp.py", line 6, in <module>
    schedulers_cpp = ctypes.CDLL(f'{Path(__file__).parent}\\cpp_extensions\\schedulers.so')
  File "C:\Users\*****\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 не является приложением Win32
```
Feels like DLL is 32-bit

**Comment by SerezD** [comment]
Hi, I have uploaded a new version where windows 64-bit dll is supported. 
Just make sure to install it before running the code: 
`pip install scheduling_utils==0.2.3`
